name: runner env

on:
  workflow_dispatch:

jobs:
  get-env:
    runs-on: self-hosted
    steps:
      - name: ENV
        run: |
          echo "1.This is runner $env:RUNNER_NAME"
          echo "2.This is runner $RUNNER_NAME"
          echo "List ENV"
          env
          wait 120
