name: runner env

on:
  workflow_dispatch:

jobs:
  get-env:
    runs-on: self-hosted
    steps:
      - name: ENV
        run: |
          echo "This is runner $RUNNER_NAME"
          echo "========"
          echo $TEST_ENV
          sleep 120
