name: Docker config

on:
  workflow_call:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load config
        run: |
          set -e
          set -x
          branch_config=$(grep -E "^${{ github.event.pull_request.head.ref }};" branch_env_config.txt)
          echo "BRANCH_CONFIG: $branch_config"
          if [[ -n "$branch_config" ]]; then
            IFS=';' read -ra config <<< "$branch_config"
            flags=""
            for val in "${config[@]:1}"; do
              flags="$flags -e $val"
            done
            echo "HERE: $flags"
            echo "FLAGS=$flags" >> $GITHUB_ENV
          else
            echo "No special flags set for branch ${{ github.event.pull_request.head.ref }}"
          fi
      - name: Read env
        run: |
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "FLAGS: ${{ env.FLAGS }}"
          echo "docker run -e TARGET=gpu${{ env.FLAGS }} -e TEST=all --device=/drv/dri  -v /src/data:/data --workdir /data docker_image:tag" 
