name: Ext comment test

on: 
  workflow_dispatch:

jobs:
  new_issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Get date
      id: current_date
      run: echo "NOW=$(date +'%m-%d-%Y')" >> $GITHUB_ENV
    - name: Create issue
      uses: dacbd/create-issue-action@v2.0.0
      id: create_issue
      with:
        token: ${{ secrets.GH_TEST_TOKEN }}
        title: WEEKLY TEST ${{ env.NOW }}
    - name: Get issue number
      run: echo "Issue Number is ${{ steps.create_issue.outputs.number }}"
    - name: Post comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        token:  ${{ secrets.GH_TEST_TOKEN }}
        issue-number: ${{ steps.create_issue.outputs.number }}
        body-path: /home/runner/work/testing/testing/ext_results.md

      
    
