name: Get comment info
on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  pull_request_review:
    types: [created, edited]

jobs:
 get_info:
   name: Get comment info
   runs-on: ubuntu-latest
   if: contains(github.event.comment.body, '!test')

   steps:
     - name: get_info
       run: |
         echo '${{ toJson(github.event.comment) }}' >> comment.json
         cat comment.json
         
