name: Matrix testing

on:
  workflow_dispatch:
    inputs:
      model1:
        type: boolean
        description: model1 desc
        required: true
      model2:
        type: boolean
        description: model2 desc
        required: true
      model3:
        type: boolean
        description: model3 desc
        required: true
jobs:
  testing_manual:
    name: Manual
    runs-on: ubuntu-latest
    steps:
      - name: check input
        run: |
          echo "manual check"
          if [ "${{ inputs.model1 }}" == "true" ]; then
            echo "model1 YES"
          else
            echo "model1 NO"
          fi
  testing_matrix:
    name: Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [model1, model2, model3, model4]
    steps:
      - name: check
        run: |
          echo "${{matrix.model}} check"
  testing_matrix2:
    name: Matrix2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [model1, model2, model3, model4]
    steps:
      - name: check
        run: |
          echo "${{matrix.model}} check"
          if [ "${{ inputs.model1 }}" == "true" ]; then
            echo "model1 YES"
          else
            echo "model1 NO"
          fi
  testing_matrix3:
    name: Matrix3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [model1, model2, model3, model4]
    steps:
      - name: check
        run: |
          echo "${{matrix.model}} check"
          export TMP=${{matrix.model}}
          #echo "TMP: $TMP"
          #if [ "${{ inputs.model1}}" == "true" ]; then
          if [ "${{ inputs.${{ env.TMP }} }}" == "true" ]; then
            echo "${{ matrix.model }} YES"
          else
            echo "${{ matrix.model }} NO"
          fi

            
    
