name: PR test
on:
#  push:
#    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  workflow_dispatch:
env:
  PR_ID: ${{github.event.number}}
  TEST_PATH: test_folder
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  test_PR:
    name: Tests PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GH_TEST_TOKEN }}
      - name: Testing
        run: |
          mkdir ${{env.TEST_PATH}}_${{env.PR_ID}}
          cd ${{env.TEST_PATH}}_${{env.PR_ID}}
          date > PR_test.txt
          cd $GITHUB_WORKSPACE
          pwd
          ls -la
          echo 'check gha ref name'
          echo $GITHUB_REF_NAME
          echo 'check git branch'
          git branch
          echo 'check git status'
          git status
          git log >> PR_test.txt
          echo 'git log from file'
          cat PR_test.txt
          echo 'try gh sha var'
          echo $GITHUB_SHA
          git config --global user.email "compy@example.com"
          git config --global user.name "compy"
          git add .
          git commit -m "PR_test update"
          #git push
          #git push origin HEAD:$GITHUB_REF_NAME
          #git push –set-upstream origin main
          echo 'PR_ID'
          echo ${{env.PR_ID}}
          echo 'old env'
          echo ${{env.TEST_PATH}}
          echo 'gh event:${{github.event_name}}'
          if ${{github.event.name}}=='pull_request'; then
            echo 'THIS IS PR EVENT'
            echo $TEST_PATH="${TEST_PATH}_${PR_ID}" >> "$GITHUB_ENV"
          else
            echo 'THIS IS NOT PR EVENT'
          fi
          #echo "::set-env name=TEST_PATH::something_${{PR_ID}"
          echo 'new env'
          echo ${{env.TEST_PATH}}
          echo 'TP var'
          echo $TEST_PATH
      - name: Cleanup
        if: ${{github.event.action=='closed' && github.event.pull_request.merged==true}}
        #if: ${{github.event.pull_request.merged==true}}
        run: |
          echo 'PR closed'
          pwd
          echo $PR_ID
          echo $GITHUB_REF_NAME

          
          
          
          
          
