name: PR test
on:
#  push:
#    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  workflow_dispatch:
env:
  PR_ID: ${{github.event.number}}
  TEST_PATH: test_folder
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  test_PR:
    name: Tests PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GH_TEST_TOKEN }}
      - name: Testing
        run: |
          pwd
          ls -la
          echo $PR_ID
          mkdir ${{env.TEST_PATH}}_${{env.PR_ID}}
          cd ${{env.TEST_PATH}}_${{env.PR_ID}}
          echo "inside test path"
          pwd
          date > PR_test.txt
          ls -la
          cd $GITHUB_WORKSPACE
          pwd
          echo 'check gha branch'
          echo $GITHUB_REF_NAME
          git branch
          git status
          git log >> PR_test.txt
          echo 'file content'
          cat PR_test.txt
          git config --global user.email "compy@example.com"
          git config --global user.name "compy"
          git add .
          git commit -m "PR_test update"
          #git push
          #git push origin HEAD:$GITHUB_REF_NAME
          #git push –set-upstream origin main
          echo 'old env'
          echo $TEST_PATH
          echo 'gh event:${{github.event_name}}'
          if ${{github.event_name=='pull_request'}}; then
            TMP_PATH=${{env.TEST_PATH}}_${{env.PR_ID}}
            echo 'TMP_PATH:'
            echo $TMP_PATH
            echo "$TEST_PATH=$TMP_PATH" >> $GITHUB_ENV
          fi
          echo 'new env'
          echo $TEST_PATH
      - name: Cleanup
        if: ${{github.event.action=='closed' && github.event.pull_request.merged==true}}
        #if: ${{github.event.pull_request.merged==true}}
        run: |
          echo 'PR closed'
          pwd
          echo $PR_ID
          echo $GITHUB_REF_NAME

          
          
          
          
          
