name: Test queue
on: 
  push:
  workflow_dispatch:

jobs:
  test_queue:
    name: one
    runs-on: ubuntu-latest
    steps: 
      - name: main
        uses: ahmadnassri/action-workflow-queue@v1
        with:
          github-token: ${{ secrets.GH_TEST_TOKEN }}
          timeout: 600000
          delay: 10000
      - name: second
        run: |
          ping -c 120 127.0.0.1
  second_job:
    name: two
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-queue@v1
        with:
          github-token: ${{ secrets.GH_TEST_TOKEN }}
          timeout: 600000
          delay: 1000 
      - name: after queue
        run:
          echo "This is executed in queue"
  
