# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas colorama tabulate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Some commands
      run: |
        pwd
        python --version
        pip list > list.txt
        git config --global user.email "compy@example.com"
        git config --global user.name "compy"
        git add .
        git commit -m "List push"
        git push
    - name: Create or Update Comment
      # You may pin to the exact commit or the version.
      # uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
      uses: peter-evans/create-or-update-comment@v2.0.0
      id: couc
      with:
        # GITHUB_TOKEN or a repo scoped PAT.
        token:  ${{ secrets.GH_TEST_TOKEN }}
        # The full name of the repository in which to create or update a comment.
        #repository: # optional
        # The number of the issue or pull request in which to create a comment.
        issue-number: 1
        # The id of the comment to update.
        #comment-id: # optional
        # The comment body.
        body: |
          My test comment
        # The mode when updating a comment, "replace" or "append".
        #edit-mode: # optional
        # Deprecated in favour of `reactions`
        #reaction-type: # optional
        # A comma separated list of reactions to add to the comment.
        #reactions: # optional
    - name: Check outputs
      run: |
        echo "Comment ID - ${{ steps.couc.outputs.comment-id }}"
