name: MIOPEN database tuning

on:
  workflow_dispatch:
  
jobs:
  release:
    uses: IgorMirosavljevicHTEC/testing/tree/main/.github/workflows/tuning.yml@main
    with:
      rocm_release: ${{ github.event.inputs.rocm_release || '5.6' }}
      benchmark_utils_repo: ${{ github.event.inputs.benchmark_utils_repo || 'ROCmSoftwarePlatform/migraphx-benchmark-utils' }}
      miopen_db_repo: ${{ github.event.inputs.miopen_db_repo || 'ROCmSoftwarePlatform/migraphx-benchmark-utils/miopen-dbs/rocm5.6' }}
      torchvision-resnet50: ${{ github.event.inputs.torchvision-resnet50 == 'true' }}
      torchvision-resnet50_fp16: ${{ github.event.inputs.torchvision-resnet50_fp16 == 'true' }}
      torchvision-densenet121: ${{ github.event.inputs.torchvision-densenet121 == 'true' }}
      torchvision-densenet121_fp16: ${{ github.event.inputs.torchvision-densenet121_fp16 == 'true' }}
      torchvision-inceptionv3: ${{ github.event.inputs.torchvision-inceptionv3 == 'true' }}
      torchvision-inceptionv3_fp16: ${{ github.event.inputs.torchvision-resnet50_fp16 == 'true' }}
      cadene-inceptionv4: ${{ github.event.inputs.cadene-inceptionv4 == 'true' }}
      cadene-resnext64x4: ${{ github.event.inputs.cadene-resnext64x4 == 'true' }}
      slim-mobilenet: ${{ github.event.inputs.slim-mobilenet == 'true' }}
      slim-nasnetalarge: ${{ github.event.inputs.slim-nasnetalarge == 'true' }}
      slim-resnet50v2: ${{ github.event.inputs.slim-resnet50v2 == 'true' }}
      bert-mrpc-onnx: ${{ github.event.inputs.bert-mrpc-onnx == 'true' }}
      bert-mrpc-tf: ${{ github.event.inputs.bert-mrpc-tf == 'true' }}
      pytorch-examples-wlang-gru: ${{ github.event.inputs.pytorch-examples-wlang-gru == 'true' }}
      pytorch-examples-wlang-lstm: ${{ github.event.inputs.pytorch-examples-wlang-lstm == 'true' }}
      torchvision-resnet50_1: ${{ github.event.inputs.torchvision-resnet50_1 == 'true' }}
      torchvision-inceptionv3_1: ${{ github.event.inputs.torchvision-inceptionv3_1 == 'true' }}
      cadene-dpn92_1: ${{ github.event.inputs.cadene-dpn92_1 == 'true' }}
      cadene-resnext101_1: ${{ github.event.inputs.cadene-resnext101_1 == 'true' }}
      slim-vgg16_1: ${{ github.event.inputs.slim-vgg16_1 == 'true' }}
      slim-mobilenet_1: ${{ github.event.inputs.slim-mobilenet_1 == 'true' }}
      slim-inceptionv4_1: ${{ github.event.inputs.slim-inceptionv4_1 == 'true' }}
      onnx-taau-downsample: ${{ github.event.inputs.onnx-taau-downsample == 'true' }}
      dlrm-criteoterabyte: ${{ github.event.inputs.dlrm-criteoterabyte == 'true' }}
      dlrm-criteoterabyte_fp16: ${{ github.event.inputs.dlrm-criteoterabyte_fp16 == 'true' }}
      agentmodel: ${{ github.event.inputs.agentmodel == 'true' }}
      unet_fp16: ${{ github.event.inputs.unet_fp16 == 'true' }}
      save_db: ${{ github.event.inputs.save_db == 'true' }}
      loop: ${{ github.event.inputs.loop == 'true' }}

      
